name: Expo Build, Test, and Submit

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  APP_ENV": "${{ secrets.APP_ENV_QA }}"
  SLUG": "${{ secrets.SLUG_QA }}"
  PROJECT_ID": "${{ secrets.PROJECT_ID_QA }}"
  BASE_URL": "${{ secrets.BASE_URL }}"
  OCP_APIM_SUBSCRIPTION_KEY": "${{ secrets.OCP_APIM_SUBSCRIPTION_KEY }}"
  GOOGLE_SERVICES": "${{ secrets.GOOGLE_SERVICES_QA }}"
  GOOGLE_SERVICES_INFO": "${{ secrets.GOOGLE_SERVICES_INFO_QA }}"
  FILE_NAME": "${{ secrets.FILE_NAME }}"

jobs:
  build-test-submit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [21, 23, 29] 
    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: yarn
        
    - name: 🏗 Setup JAVA JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: "17"
          distribution: "temurin"

    - name: 🏗 Setup Android SDK
      uses: android-actions/setup-android@v3 #default is version 10406996 (short version 11.0)
      with:
        api-level: 29

    - name: 🏗 Setup EAS
      uses: expo/expo-github-actions@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile
        
    - name: ⚙️ Build APK
      id: build_apk
      env:
          EAS_BUILD_PROFILE: preview
      run: |
        eas build --local --platform android --profile preview --output=./${{ env.FILE_NAME }}

    - name: ✅ Check build result
      if: success()
      run: echo "Build successful 🎉"

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      
    - name: Set up Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: echo "Emulator is ready"
        
    - name: Install APK on emulator
      run: |
        APK_PATH=$(find . -name "*.apk" | head -n 1)
        adb install $APK_PATH
        
    - name: Install Maestro
      run: |
        curl -Ls "https://get.maestro.mobile.dev" | bash
        export PATH="$PATH":"$HOME/.maestro/bin"
        
    - name: Run Maestro tests
      run: maestro test maestro/test.yaml