name: Build App
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS to build on. Ubuntu is faster, MacOS supports iOS builds
        options:
          - macos-latest
          - ubuntu-latest
      platform:
        type: choice
        description: Platform to build for
        options:
          - android
          - ios
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production
      should_submit:
        type: boolean
        description: Whether to perform the submit step
        required: true
        default: false
jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}
    steps:
    - name: 🔎 Check EXPO_TOKEN
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "EXPO_TOKEN not found must be configured within github"
          exit 1
        fi

    - name: 💡 Set Google Services
      run: |
        echo "${{ secrets.GOOGLE_SERVICES }}" | base64 --decode > ./google-services.json
          echo "${{ secrets.GOOGLE_SERVICES_INFO }}" | base64 --decode > ./GoogleService-Info.plist

    - name: 🔍 Check google-services.json and GoogleService-Info.plist
      run: |
        if [ ! -f "google-services.json" ]; then
            echo "google-services.json not found in the project root"
            exit 1
          fi
          if [ ! -f "GoogleService-Info.plist" ]; then
            echo "GoogleService-Info.plist not found in the project root"
            exit 1
          fi

    - name: 🏗 Setup repo
      uses: actions/checkout@v2

    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: yarn

    - name: 🏗 Setup JAVA JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: "17"
          distribution: "temurin"

    - name: 🏗 Setup Android SDK
      uses: android-actions/setup-android@v3 #default is version 10406996 (short version 11.0)
      with:
        api-level: 29

    - name: 🏗 Setup Expo and EAS
      uses: expo/expo-github-action@v7
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile

    - name: 📋 Test project
      run: yarn test

    - name: 👷 Build app
      run: |
        eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=${{ github.event.inputs.platform }} \
          --profile=${{ github.event.inputs.profile }}

    - name: 🚢 Submit
      if: ${{ github.event.inputs.should_submit }}
      run: eas submit -p ${{ github.event.inputs.platform }} --profile ${{ github.event.inputs.profile }} --path app-build